#!/bin/bash

for things  in rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpio07 rpi08 rpi09 rpi010 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18;
do 
	ping  -W 1 -c 1 $thing &>/dev/null
	if [ $? -eq 0 ] ;
	then
		echo  "$things : active"
	else
		echo "$things : dead"
	fi
done
